"""Initial migration.

Revision ID: ddc1186ac3cb
Revises: 
Create Date: 2024-06-30 13:54:48.733132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc1186ac3cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('business_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('category_product',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=80), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('transaction',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_table('product',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=False),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category_product.id_category'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('detail_transaction',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('qty_purchases', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_table('restock',
    sa.Column('id_restock', sa.Integer(), nullable=False),
    sa.Column('restock_date', sa.DateTime(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('qty_restock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.PrimaryKeyConstraint('id_restock')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restock')
    op.drop_table('detail_transaction')
    op.drop_table('product')
    op.drop_table('transaction')
    op.drop_table('category_product')
    op.drop_table('user')
    # ### end Alembic commands ###
